account/urls.py
from django.urls import path 
from account import views

urlpatterns = [
    path('signup/', views.signup, name ='signup'),
    path('login/', views.login, name ='login'),
    path('logout/', views.logout, name ='logout'),
]

crud/urls.py
from django.contrib import admin #django.contrib에서 admin을 불러온다.
from django.urls import path #django.urls에서 path를 불러온다.
import blog.views # blog의 views를 불러온다.
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('base/', blog.views.base, name='base'), #사이트 경로 지정  
    path('', blog.views.main, name='main'), #''은 사이트를 먼저 켰을때, 제일 먼저 뜨는 페이지로 설정. 이름은 main으로 정한다.
    path('write/create/', blog.views.create, name='create'), #write/create로 경로지정을하고 이름은 create로 정한다.
    path('edit/<str:id>/', blog.views.edit, name='edit'), #edit와 문자열 id를받아 경로를 지정하고 이름은 edit으로 정한다.
    path('detail/<str:id>/', blog.views.detail, name='detail'), #detail과 문자열 id를받아 경로를 지정하고 이름은 detail으로 정한다.
    path('delete/<str:id>/', blog.views.delete, name='delete'), #delete와 문자열 id를받아 경로를 지정하고 이름은 delete으로 정한다.
    path('hashtag/', blog.views.hashtagform, name='hashtag'),
    path('<int:hashtag_id>/search/',blog.views.search, name ='search'),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    age = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)

blog/models.py
from django.db import models # django.db로부터 models를 불러와라
from django.conf import settings # django.conf로부터 settings를 불러와라
# Create your models here.

class Blog(models.Model): #클래스 Blog 선언
    title = models.CharField(max_length=200) #제목은 최대길이 200으로 charfield로 받는다.
    pub_date = models.DateField('date published') #날짜와 시간은 model의 datefield로 작성된다.
    writer = models.CharField(max_length=15, default='닉네임을 입력해주세요') #글쓴이는 model의 charfield로 받되, 최대길이는 15이고 이름을 입력하기 이전에 '닉네임을 입력해주세요'를 먼저 띄운다.
    content = models.TextField() # 내용을 model의 textfield를 이용하여 받는다. 글자제한 x
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='images/', blank = True)

    def __str__(self): #함수 __str__선언
        return self.title # 게시물의 제목을 입력한대로 반환한다.

class Comment(models.Model):
    def __str__(self):
        return self.text
        
    post_id = models.ForeignKey(Blog,on_delete=models.CASCADE, related_name = 'comments')
    text = models.CharField(max_length=50)

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

account/forms.py
from django.contrib.auth import forms
from .models import CustomUser

class CustomUserCreationForm(forms.UserCreationForm):
    class Meta:
        model = CustomUser
        fields = forms.UserCreationForm.Meta.fields + ('age', 'address',)

class CustomUserChangeForm(forms.UserChangeForm):
    class Meta:
        model = CustomUser
        fields = forms.UserChangeForm.Meta.fields

blog/forms.py
from django import forms #django로부터 forms를 불러온다.
from .models import Blog,Comment,Hashtag #.models로부터 Blog를 불러온다.

class PostForm(forms.ModelForm): #POSTFORM을 선언한다.
    class Meta: 
        model = Blog #model에 Blog 객체를 저장한다. 
        fields = ['title','writer','content','hashtags','image'] #fields에 title,writer,content 배열을 만든다.

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

account/views.py
from django.shortcuts import render,redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'account/signup.html', {'form':form})
        
    else:
        form = CustomUserCreationForm()
        return render(request, 'account/signup.html', {'form':form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'account/login.html', {'form':form})
        
    else:
        form = AuthenticationForm()
        return render(request, 'account/login.html', {'form':form})

def logout(requset):
    auth.logout(requset)
    return redirect('main')

blog/views.py
from django.shortcuts import render ,redirect, get_object_or_404 #django.shortcuts에서 기능들을 이용할 수 있도록 render,redirect,get_object_or_404를 불러온다. 
from .models import Blog,Hashtag #.models에서 Blog를 불러온다.
from .forms import PostForm,CommentForm,HashtagForm #.forms에서 PostForm을 불러온다.
from django.utils import timezone #시간을 이용하기 위해 django.utils에서 timezone을 불러온다.

# Create your views here.
def base(request): #함수 base를 선언
    return render(request, 'blog/base.html') #render을 이용하여 blog/base.html을 띄운다.

#메인페이지
def main(request): #메인함수 선언
    posts = Blog.objects #posts에 Blog의 모든 객체를 저장
    hashtags = Hashtag.objects
    return render(request, 'blog/main.html', {'posts':posts, 'hashtags':hashtags}) #요청되었을때 posts를 모두 띄운다.

#글쓰기 페이지
def write(request): #함수 write선언
    return render(request, 'blog/write.html') #요청되었을 때, write.html을 띄운다.

#글쓰기 함수
        
#편집페이지
def edit(request,id): #edit함수 선언
    post = get_object_or_404(Blog, id=id) #post에 id를받고 
    if request.method == 'POST': # 만약 request.method가 POST면
        form = PostForm(request.POST, instance=post) #form은 PostForm에 request.POST와 INSTANCE=POST를 받은 값이다.
        if form.is_valid(): #만약 form.is_valid가 true이면
            form.save(commit=False) #Fform을 저장한다.
            form.save() #변경된 내용들을 모두 저장한다.
            return redirect('main') #그리고 메인페이지로 돌아간다.
    else:
        form = PostForm(instance=post) #form은 PostForm에 instance이 post와 같은 값이다.
        return render(request, 'blog/edit.html',{'form':form}) #form과 edit.html을 반환한다.

def detail(request,id): #함수 detail을 선언하고 요청되었을때 id를 받는다.
    post = get_object_or_404(Blog, id=id) #post에 get_object_or_404에 BLOG와 ID를 받은 값을 저장한다.
    hashtags = Hashtag.objects
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = post
            comment.text = form.cleaned_data['text']
            comment.save()
            return redirect('detail',id)
    else:
        form = CommentForm()
        return render(request, 'blog/detail.html',{'post':post, 'form':form}) #post를 띄운다

def delete(request,id): #delete함수 선언
    post = get_object_or_404(Blog, id=id) #post에 get_object_or_404에 BLOG와 ID를 받은 값을 저장한다.
    post.delete() #post를 지운다.
    return redirect('main') #그리고 메인페이지로 돌아간다.

def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'blog/hashtag.html', {'form':form, "error_message":error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
            return redirect('main')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html', {'form':form})

def create(request, blog=None):
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.datetime.now()
            post.save()
            form.save_m2m()
            return redirect('main')
    else:
        form = PostForm(instance=blog)
        return render(request, 'blog/write.html', {'form':form})


def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'blog/search.html', {'hashtag':hashtag})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stylish Portfolio - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'blog/blogassets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <a class="menu-toggle rounded" href="#"><i class="fas fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-nav-item"><a href="{% url 'main' %}">홈</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'create' %}">글 작성</a></li>             
                <li class="sidebar-nav-item"><a href="{% url 'hashtag' %}">해시태그</a></li>
                {% if user.is_active %}
                    <li class="sidebar-nav-item"><a href="{% url 'logout' %}">로그아웃</a></li>
                    <li class="sidebar-nav-item"><a>{{ user.username }}님 안녕하세요.</a></li>
                {% else %}
                    <li class="sidebar-nav-item"><a href="{% url 'login' %}">로그인</a></li>
                    <li class="sidebar-nav-item"><a href="{% url 'signup' %}">회원 가입</a></li>
                {% endif %}
            </ul>
        </nav>
        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">Stylish Portfolio</h1>
                <h3 class="mb-5"><em>A Free Bootstrap Theme by Start Bootstrap</em></h3>
                <a class="btn btn-primary btn-xl" href="{% url 'create' %}">create Out More</a>
            </div>
        </header>
        {% block content %}
        <!--이곳에 block content를 만들어 상속을 한다.-->
        {% endblock %}
        <!-- Services-->
        <section class="content-section bg-primary text-white text-center" id="services">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading">
                    <h3 class="text-secondary mb-0">Services</h3>
                    <h2 class="mb-5">What We Offer</h2>
                </div>
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-screen-smartphone"></i></span>
                        <h4><strong>Responsive</strong></h4>
                        <p class="text-faded mb-0">Looks great on any screen size!</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>
                        <h4><strong>Redesigned</strong></h4>
                        <p class="text-faded mb-0">Freshly redesigned for Bootstrap 5.</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-like"></i></span>
                        <h4><strong>Favorited</strong></h4>
                        <p class="text-faded mb-0">
                            Millions of users
                            <i class="fas fa-heart"></i>
                            Start Bootstrap!
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-mustache"></i></span>
                        <h4><strong>Question</strong></h4>
                        <p class="text-faded mb-0">I mustache you a question...</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Callout-->
        <section class="callout">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mx-auto mb-5">
                    Welcome to
                    <em>your</em>
                    next website!
                </h2>
                <a class="btn btn-primary btn-xl" href="https://startbootstrap.com/theme/stylish-portfolio/">Download Now!</a>
            </div>
        </section>
        <!-- Portfolio-->
        <section class="content-section" id="portfolio">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading text-center">
                    <h3 class="text-secondary mb-0">Portfolio</h3>
                    <h2 class="mb-5">Recent Projects</h2>
                </div>
                <div class="row gx-0">
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="#!">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Stationary</div>
                                    <p class="mb-0">A yellow pencil with envelopes on a clean, blue backdrop!</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static 'blog/assets/img/portfolio-1.jpg' %}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="#!">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Ice Cream</div>
                                    <p class="mb-0">A dark blue background with a colored pencil, a clip, and a tiny ice cream cone!</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static 'blog/assets/img/portfolio-2.jpg' %}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="#!">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Strawberries</div>
                                    <p class="mb-0">Strawberries are such a tasty snack, especially with a little sugar on top!</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static 'blog/assets/img/portfolio-3.jpg' %}" alt="..." />
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="#!">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Workspace</div>
                                    <p class="mb-0">A yellow workspace with some scissors, pencils, and other objects.</p>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static 'blog/assets/img/portfolio-4.jpg' %}" alt="..." />
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Call to Action-->
        <section class="content-section bg-primary text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">The buttons below are impossible to resist...</h2>
                <a class="btn btn-xl btn-light me-4" href="#!">Click Me!</a>
                <a class="btn btn-xl btn-dark" href="#!">Look at Me!</a>
            </div>
        </section>
        <!-- Map-->
        <div class="map" id="contact">
            <iframe src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
            <br />
            <small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a></small>
        </div>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white" href="#!"><i class="icon-social-github"></i></a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Your Website 2021</p>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %} <!--base.html의 내용을 상속한다.-->
{% block content %} <!--base.html에 선언된 block content에 이 내용을 덮어씌운다.-->
    <h2>제목 : {{post.title}}</h2> <!--제목은 post.title로 정한다.-->
    <p>작성 일자 및 시간 :{{ post.pub_date }}</p> <!--작성 일자 및 시간에 post.pub_date로 설정-->
    <p>글쓴이 : {{post.writer}}</p> <!--글쓴이는 post.wirter로 정한다.-->
    <p>내용 : {{post.content}}</p> <!--내용은 post의 content로 정한다.-->

    {% if post.image %}
        <img src="{{post.image.url}}" width="250" height="250" alt="Card image cap">
    {% endif%}
    <p></p>
    {% for hashtag in post.hashtags.all %}
        {{hashtag.name}}
    {% endfor %}
    
    <p></p>
    <a href="{% url 'edit' post.id %}">수정하기</a> <!--버튼을 만들어 하이퍼링크를 지정해준다. edit으로 연결되는 버튼-->
    <a href="{% url 'delete' post.id %}">삭제하기</a> <!--버튼을 만들어 delete기능을 지정해준다. delete으로 연결되는 버튼-->
    {% for comment in post.comments.all %}
        <p>{{comment.text}}</p>
    {% endfor %}
    <p></p>
    <form method = "POST" action="{% url 'detail' post.id %}">
        {%csrf_token%}
        <p>{{form.as_p}}</p>
        <input type="submit" value  ="submit">
    </form>
{% endblock %} <!--여기서 block을 끝낸다-->

blog/templates/blog/edit.html
{% extends 'blog/base.html' %} <!--base.html을 상속한다.-->

{% block content %}
<section class="content-section bg-light" id="about">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-10">
                <h2>오늘의 일기를 여기다가 작성해보세요!</h2> 
                <p class="lead mb-5">                           
                    <form method ="POST"> <!--입력받는 방식은 POST이다.-->
                        {% csrf_token %} <!--보안상을 위해 써주는 코드-->
                        <table>
                            {{form.as_table}} <!--form.as_table을 띄운다.-->
                        </table>
                        <button class="btn btn-dark btn-xl" type="submit">수정하기</button> <!--제출 type의 버튼을 만들어 수정기능을 만든다.-->
                    </form>
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/hashtag.html
{% extends 'blog/base.html' %}

{% block content %}
<section class="content-section bg-light" id="about">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-10">
                <h2>New Hashtag</h2>
                <p class="lead mb-5">  
                    {{ error_message }}                         
                    <form method ="POST"> <!--입력받는 방식은 POST로 입력받는다-->
                        {% csrf_token %} <!--보안상의 문제로 코드 입력-->
                        <table>
                            {{form.as_table}}<!--form.as_table을 띄운다-->
                        </table>
                        <button class="btn btn-dark btn-xl" type="submit">작성</button><!--제출 형식의 버튼을 만들어 주어 작성 기능을 가진 버튼을 생성-->
                    </form>
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/main.html
{% extends 'blog/base.html' %} <!--base.html을 상속한다.-->
 
{% block content%} 
<section class="content-section bg-light" id="about">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-10">
                <h2>글 목록!</h2>


                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Hashtag 검색
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">

                    {% for hashtag in hashtags.all %}
                    <li><a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{hashtag.name}}</a></li>
                    {% endfor %}
                  </ul>
                </div>

                <p class="lead mb-5">                           
                    {% for posts in posts.all %} <!--posts.all의 모든  -->
                    <p>제목 :<a href="{% url 'detail' posts.id %}">{{posts.title}}</a></p>
                    <p>작성자 : {{posts.writer}}</p>
                    <p>작성 일지 및 시간: {{posts.pub_date}}</p>

                    {% if posts.image %}
                      <img src="{{posts.image.url}}" width="250" height="250" alt="Card image cap">
                    {% endif %}
                    <hr>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %} <!--base.html을 상속한다.-->
 
{% block content%} 
<section class="content-section bg-light" id="about">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-10">
                <h1>{{ hashtag }}가 있는 게시글 목록</h1>
                <span>해시태그 검색결과 페이지 입니다.</span>
            </div>
            {% for post in hashtag.blog_set.all %}
                <a href="{% url 'detail' post.id %}">
                    <h2>{{post.title}}</h2>

                    <h3>{{post.summary}}</h3>
                </a>
                <p>{{post.pub_date}}</p>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/write.html
{% extends 'blog/base.html' %}

{% block content %}
<section class="content-section bg-light" id="about">
    <div class="container px-4 px-lg-5 text-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-10">
                <h2>오늘의 일기를 여기다가 작성해보세요!</h2>
                <p class="lead mb-5">                           
                    <form method ="POST" enctype="multipart/form-data"> <!--입력받는 방식은 POST로 입력받는다-->
                        {% csrf_token %} <!--보안상의 문제로 코드 입력-->
                        <table>
                            {{form.as_table}}<!--form.as_table을 띄운다-->
                        </table>
                        <button class="btn btn-dark btn-xl" type="submit">작성</button><!--제출 형식의 버튼을 만들어 주어 작성 기능을 가진 버튼을 생성-->
                    </form>
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}